version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # Reads environment variables from .env file
    environment:
      APP_PORT: ${APP_PORT}
      METRICS_PORT: ${METRICS_PORT}
      LOG_LEVEL: ${LOG_LEVEL}
      MAX_CHUNK_SIZE: ${MAX_CHUNK_SIZE}
      MIN_CHUNK_SIZE: ${MIN_CHUNK_SIZE}
      N_LIMIT: ${N_LIMIT}
    ports:
      - "${APP_PORT}:${APP_PORT}"
      - "${METRICS_PORT}:${METRICS_PORT}"
    networks:
      - metrics

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    networks:
      - metrics

  grafana:
    image: grafana/grafana-oss:latest
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./monitoring/dashboards/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./monitoring/dashboards:/var/lib/grafana/dashboards
    networks:
      - metrics

networks:
  metrics:
    driver: bridge
